# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 531065a33d88095ce3d06a537c5097f9b48c62112c0ef1461e96cca03d969a93ed52c43b6fee4fa9f804ef9e873e5390fcc2bd58345f35d536c349d10de914d5

test:
  secret_key_base: 655844e4fa35940b5aae014dc36450d66a160ff0481f0fee8403c6842ef9b3ad80df3075a3ff8849d8576c2c4290b353425754a1ccdce31c29144a0358b6c5f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
